# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Ankit Kamboj"
title_separator          : "-"
name                     : &name "Ankit Kamboj"
description              : &description "A web space to enable learning and skill upgradation"

# URL and baseurl should be commented for development.
url                      : # "http://ankitkamboj.com" # the base hostname & protocol for your site e.g. "https://kambojankit.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
# gh_repo                :
teaser                   : /teaser/default-code.png # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
# breadcrumbs              : true # true, false (default)
words_per_minute         : 200
comments:
  provider               : "disqus" # false (default), "disqus", "facebook", "google-plus", custom"
  disqus:
    shortname            : "ankitkamboj" # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                : "504921009700105"
    num_posts            : 5 # 5 (default)
    colorscheme          : "light" # "light" (default), "dark"

# SEO Related
google_site_verification : "BYwbocmFPGHLSRFgB7q5jlq7mCxDuBcZ2cAYRAo_wpM"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter "KambojAnkie"
facebook:
  username               : &facebook "kambojankie"
  app_id                 : "504921009700105"
  publisher              :
og_image                 : "site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://in.linkedin.com/in/ankitkamboj"
    - "https://github.com/kambojankit"
    - "https://twitter.com/kambojankie"
    - "https://facebook.com/kambojankie"
    - "https://plus.google.com/+AnkitKambojj"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-78633920-2"

# Google AdSense
google_ad_client         :
google_ad_slot           :


# Site Author
author:
  name             : "Ankit Kamboj"
  avatar           : "AnkitKamboj.jpg"
  bio              : "I am a Software Consultant and Trainer, and an avid sports enthusiast."
  location         : "Gurgaon, India"
  email            : "connect@ankitkamboj.com"
  uri              : "http://ankitkamboj.com"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         : "kambojankie"
  foursquare       :
  github           : "kambojankit"
  google_plus      : # "AnkitKambojj"
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "ankitkamboj"
  pinterest        :
  soundcloud       :
  stackoverflow    : # "1436980/kambojankit" # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "kambojankie"
  vine             :
  weibo            :
  xing             :
  youtube          : # "AnkitKambojj"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
# ==============================================================
#           Training Collections
# ==============================================================
  train-framework:
    output: true
    permalink: /:collection/:path/
  train-language:
    output: true
    permalink: /:collection/:path/
  train-tdd:
    output: true
    permalink: /:collection/:path/
  train-tools:
    output: true
    permalink: /:collection/:path/
# ==============================================================
#           Tutrials Collections Defaults
# ==============================================================
  tut-java:
    output: true
    permalink: /:collection/:path/
# ==============================================================
#           Products Collections Defaults
# ==============================================================
  products:
    output: true
    permalink: /:collection/:path/

# Defaults for posts, pages and our collections
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# ==============================================================
#           Trainings Collections Defaults
# ==============================================================
  # train-framework
  - scope:
      path: ""
      type: train-framework
    values:
      layout: single
      author_profile: true
      share: true

  # train-language
  - scope:
      path: ""
      type: train-language
    values:
      layout: single
      author_profile: true
      share: true

  # train-tdd
  - scope:
      path: ""
      type: train-language
    values:
      layout: single
      author_profile: true
      share: true

  # train-tools
  - scope:
      path: ""
      type: train-tools
    values:
      layout: single
      author_profile: true
      share: true

# ==============================================================
#           Tutrials Collections Defaults
# ==============================================================

  # tut-java
  - scope:
      path: ""
      type: tut-java
    values:
      layout: single
      author_profile: false
      share: true
      read_time: false
      comments: true
      sidebar:
        nav: "tut-java"

# ==============================================================
#           Products Collections Defaults
# ==============================================================

  # products
  - scope:
      path: ""
      type: products
    values:
      layout: single
      author_profile: true
      share: true
      read_time: false
      comments: true

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Asia/Kolkata # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
categories:
  type: liquid
  path: /categories/
tags:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
